#pragma once

#ifdef RNBO_DESCRIPTION_AS_STRING

namespace RNBO {
	const std::string patcher_description(
			R"RNBOLIT({
  "parameters": [
    {
      "type": "ParameterTypeNumber",
      "index": 0,
      "name": "run",
      "paramId": "run",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      )RNBOLIT"
R"RNBOLIT("index": 1,
      "name": "waveshape",
      "paramId": "waveshape",
      "minimum": 0,
      "maximum": 1024,
      "exponent": 1,
      "steps": 0,
      "initialValue": 512,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 2,
      "name": "8va",
      "paramId": "8)RNBOLIT"
R"RNBOLIT(va",
      "minimum": -4,
      "maximum": 4,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 3,
      "name": "globalTempo",
      "paramId": "globalTempo",
      "minimum": 1,
      "maximum": 500,
     )RNBOLIT"
R"RNBOLIT( "exponent": 1,
      "steps": 0,
      "initialValue": 120,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 4,
      "name": "stepLen",
      "paramId": "stepLen",
      "minimum": 4,
      "maximum": 64,
      "exponent": 1,
      "steps": 0,
      "initialValue": 16)RNBOLIT"
R"RNBOLIT(,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 5,
      "name": "synthLvl",
      "paramId": "synthLvl",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 1,
      "isEnum": false,
      "enumValues": [],
      "dis)RNBOLIT"
R"RNBOLIT(playName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 6,
      "name": "root",
      "paramId": "root",
      "minimum": 0,
      "maximum": 127,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug":)RNBOLIT"
R"RNBOLIT( false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 7,
      "name": "genMel",
      "paramId": "genMel",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
     )RNBOLIT"
R"RNBOLIT( "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 8,
      "name": "genMelAlways",
      "paramId": "genMelAlways",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "ty)RNBOLIT"
R"RNBOLIT(pe": "ParameterTypeNumber",
      "index": 9,
      "name": "scale",
      "paramId": "scale",
      "minimum": 0,
      "maximum": 10,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 10,
      "name": "ve)RNBOLIT"
R"RNBOLIT(rbLvl",
      "paramId": "verbLvl",
      "minimum": 0,
      "maximum": 100,
      "exponent": 1,
      "steps": 0,
      "initialValue": 66,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 11,
      "name": "genBass",
      "paramId": "genBass",
      "minimum": 0,
 )RNBOLIT"
R"RNBOLIT(     "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 12,
      "name": "bassLvl",
      "paramId": "bassLvl",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
  )RNBOLIT"
R"RNBOLIT(    "initialValue": 0.6,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 13,
      "name": "genKck",
      "paramId": "genKck",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumVal)RNBOLIT"
R"RNBOLIT(ues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 14,
      "name": "kckLvl",
      "paramId": "kckLvl",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0.5,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      ")RNBOLIT"
R"RNBOLIT(order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 15,
      "name": "hatLvl",
      "paramId": "hatLvl",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0.3,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
    )RNBOLIT"
R"RNBOLIT(  "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 16,
      "name": "genHat",
      "paramId": "genHat",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    })RNBOLIT"
R"RNBOLIT(,
    {
      "type": "ParameterTypeNumber",
      "index": 17,
      "name": "atk",
      "paramId": "mainSynthVoice/atk",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
    )RNBOLIT"
R"RNBOLIT(  "index": 18,
      "name": "1/atk",
      "paramId": "mainSynthVoice/1/atk",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 19,
      "name": "2/atk",
      ")RNBOLIT"
R"RNBOLIT(paramId": "mainSynthVoice/2/atk",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 20,
      "name": "3/atk",
      "paramId": "mainSynthVoice/3/atk",
      "mini)RNBOLIT"
R"RNBOLIT(mum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 21,
      "name": "dec",
      "paramId": "mainSynthVoice/dec",
      "minimum": 0.1,
      "maximum": 200,
      "exponent")RNBOLIT"
R"RNBOLIT(: 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 22,
      "name": "1/dec",
      "paramId": "mainSynthVoice/1/dec",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": )RNBOLIT"
R"RNBOLIT(0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 23,
      "name": "2/dec",
      "paramId": "mainSynthVoice/2/dec",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues":)RNBOLIT"
R"RNBOLIT( [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 24,
      "name": "3/dec",
      "paramId": "mainSynthVoice/3/dec",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": ")RNBOLIT"
R"RNBOLIT(",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 25,
      "name": "sus",
      "paramId": "mainSynthVoice/sus",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "vis)RNBOLIT"
R"RNBOLIT(ible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 26,
      "name": "1/sus",
      "paramId": "mainSynthVoice/1/sus",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "io)RNBOLIT"
R"RNBOLIT(Type": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 27,
      "name": "2/sus",
      "paramId": "mainSynthVoice/2/sus",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type)RNBOLIT"
R"RNBOLIT(": "ParameterTypeNumber",
      "index": 28,
      "name": "3/sus",
      "paramId": "mainSynthVoice/3/sus",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 29,
    )RNBOLIT"
R"RNBOLIT(  "name": "rel",
      "paramId": "mainSynthVoice/rel",
      "minimum": 0.1,
      "maximum": 2000,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 30,
      "name": "1/rel",
      "paramId": "mainSynthVo)RNBOLIT"
R"RNBOLIT(ice/1/rel",
      "minimum": 0.1,
      "maximum": 2000,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 31,
      "name": "2/rel",
      "paramId": "mainSynthVoice/2/rel",
      "minimum": 0.1,
      "max)RNBOLIT"
R"RNBOLIT(imum": 2000,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 32,
      "name": "3/rel",
      "paramId": "mainSynthVoice/3/rel",
      "minimum": 0.1,
      "maximum": 2000,
      "exponent": 1,
      "ste)RNBOLIT"
R"RNBOLIT(ps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 33,
      "name": "slide",
      "paramId": "BassLine/slide",
      "minimum": 0,
      "maximum": 100,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": fals)RNBOLIT"
R"RNBOLIT(e,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 34,
      "name": "atk",
      "paramId": "BassLine/atk",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
   )RNBOLIT"
R"RNBOLIT(   "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 35,
      "name": "dec",
      "paramId": "BassLine/dec",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
)RNBOLIT"
R"RNBOLIT(      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 36,
      "name": "sus",
      "paramId": "BassLine/sus",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "io)RNBOLIT"
R"RNBOLIT(Type": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 37,
      "name": "rel",
      "paramId": "BassLine/rel",
      "minimum": 0.1,
      "maximum": 2000,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    }
  ],
  "numParameters":)RNBOLIT"
R"RNBOLIT( 38,
  "numSignalInParameters": 0,
  "numSignalOutParameters": 0,
  "numInputChannels": 0,
  "numOutputChannels": 2,
  "numMidiInputPorts": 0,
  "numMidiOutputPorts": 0,
  "transportUsed": false,
  "externalDataRefs": [],
  "patcherSerial": 0,
  "inports": [
    {
      "tag": "in2",
      "meta": ""
    },
    {
      "tag": "in3",
      "meta": ""
    },
    {
      "tag": "in4",
      "meta": ""
    },
    {
      "tag": "in5",
      "meta": ""
    }
  ],
  "outports": [
    {
      "tag": "o)RNBOLIT"
R"RNBOLIT(ut3",
      "meta": ""
    },
    {
      "tag": "out4",
      "meta": ""
    },
    {
      "tag": "out5",
      "meta": ""
    },
    {
      "tag": "out6",
      "meta": ""
    }
  ],
  "inlets": [
    {
      "type": "event",
      "index": 2,
      "tag": "in2",
      "meta": "",
      "comment": "Synth Seq In"
    },
    {
      "type": "event",
      "index": 3,
      "tag": "in3",
      "meta": "",
      "comment": "Bass Seq In"
    },
    {
      "type": "event",
      "index": 4,
     )RNBOLIT"
R"RNBOLIT( "tag": "in4",
      "meta": "",
      "comment": "Kck Seq In"
    },
    {
      "type": "event",
      "index": 5,
      "tag": "in5",
      "meta": "",
      "comment": "Hat Seq In"
    }
  ],
  "outlets": [
    {
      "type": "signal",
      "index": 1,
      "tag": "out1",
      "meta": ""
    },
    {
      "type": "signal",
      "index": 2,
      "tag": "out2",
      "meta": ""
    },
    {
      "type": "event",
      "index": 3,
      "tag": "out3",
      "meta": "",
      "comment": )RNBOLIT"
R"RNBOLIT("Melody Sequence"
    },
    {
      "type": "event",
      "index": 4,
      "tag": "out4",
      "meta": "",
      "comment": "Bass Sequence"
    },
    {
      "type": "event",
      "index": 5,
      "tag": "out5",
      "meta": "",
      "comment": "Bass Sequence"
    },
    {
      "type": "event",
      "index": 6,
      "tag": "out6",
      "meta": "",
      "comment": "Hat Sequence"
    }
  ],
  "presetid": "rnbo",
  "meta": {
    "architecture": "x64",
    "filename": "2025-03-06_Hopki)RNBOLIT"
R"RNBOLIT(nsSeq.maxpat",
    "rnboobjname": "rnbomatic",
    "maxversion": "9.0.5",
    "rnboversion": "1.3.4",
    "name": "seqv2"
  }
})RNBOLIT"
		);

	const std::string patcher_presets(
			R"RNBOLIT({})RNBOLIT"
		);
}

#else

#include <json/json.hpp>

namespace RNBO {
	const nlohmann::json patcher_description = nlohmann::json::parse(
			std::string(
				R"RNBOLIT({
  "parameters": [
    {
      "type": "ParameterTypeNumber",
      "index": 0,
      "name": "run",
      "paramId": "run",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      )RNBOLIT"
R"RNBOLIT("index": 1,
      "name": "waveshape",
      "paramId": "waveshape",
      "minimum": 0,
      "maximum": 1024,
      "exponent": 1,
      "steps": 0,
      "initialValue": 512,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 2,
      "name": "8va",
      "paramId": "8)RNBOLIT"
R"RNBOLIT(va",
      "minimum": -4,
      "maximum": 4,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 3,
      "name": "globalTempo",
      "paramId": "globalTempo",
      "minimum": 1,
      "maximum": 500,
     )RNBOLIT"
R"RNBOLIT( "exponent": 1,
      "steps": 0,
      "initialValue": 120,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 4,
      "name": "stepLen",
      "paramId": "stepLen",
      "minimum": 4,
      "maximum": 64,
      "exponent": 1,
      "steps": 0,
      "initialValue": 16)RNBOLIT"
R"RNBOLIT(,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 5,
      "name": "synthLvl",
      "paramId": "synthLvl",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 1,
      "isEnum": false,
      "enumValues": [],
      "dis)RNBOLIT"
R"RNBOLIT(playName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 6,
      "name": "root",
      "paramId": "root",
      "minimum": 0,
      "maximum": 127,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug":)RNBOLIT"
R"RNBOLIT( false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 7,
      "name": "genMel",
      "paramId": "genMel",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
     )RNBOLIT"
R"RNBOLIT( "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 8,
      "name": "genMelAlways",
      "paramId": "genMelAlways",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "ty)RNBOLIT"
R"RNBOLIT(pe": "ParameterTypeNumber",
      "index": 9,
      "name": "scale",
      "paramId": "scale",
      "minimum": 0,
      "maximum": 10,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 10,
      "name": "ve)RNBOLIT"
R"RNBOLIT(rbLvl",
      "paramId": "verbLvl",
      "minimum": 0,
      "maximum": 100,
      "exponent": 1,
      "steps": 0,
      "initialValue": 66,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 11,
      "name": "genBass",
      "paramId": "genBass",
      "minimum": 0,
 )RNBOLIT"
R"RNBOLIT(     "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 12,
      "name": "bassLvl",
      "paramId": "bassLvl",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
  )RNBOLIT"
R"RNBOLIT(    "initialValue": 0.6,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 13,
      "name": "genKck",
      "paramId": "genKck",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumVal)RNBOLIT"
R"RNBOLIT(ues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 14,
      "name": "kckLvl",
      "paramId": "kckLvl",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0.5,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      ")RNBOLIT"
R"RNBOLIT(order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 15,
      "name": "hatLvl",
      "paramId": "hatLvl",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0.3,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
    )RNBOLIT"
R"RNBOLIT(  "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 16,
      "name": "genHat",
      "paramId": "genHat",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    })RNBOLIT"
R"RNBOLIT(,
    {
      "type": "ParameterTypeNumber",
      "index": 17,
      "name": "atk",
      "paramId": "mainSynthVoice/atk",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
    )RNBOLIT"
R"RNBOLIT(  "index": 18,
      "name": "1/atk",
      "paramId": "mainSynthVoice/1/atk",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 19,
      "name": "2/atk",
      ")RNBOLIT"
R"RNBOLIT(paramId": "mainSynthVoice/2/atk",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 20,
      "name": "3/atk",
      "paramId": "mainSynthVoice/3/atk",
      "mini)RNBOLIT"
R"RNBOLIT(mum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 21,
      "name": "dec",
      "paramId": "mainSynthVoice/dec",
      "minimum": 0.1,
      "maximum": 200,
      "exponent")RNBOLIT"
R"RNBOLIT(: 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 22,
      "name": "1/dec",
      "paramId": "mainSynthVoice/1/dec",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": )RNBOLIT"
R"RNBOLIT(0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 23,
      "name": "2/dec",
      "paramId": "mainSynthVoice/2/dec",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues":)RNBOLIT"
R"RNBOLIT( [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 24,
      "name": "3/dec",
      "paramId": "mainSynthVoice/3/dec",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": ")RNBOLIT"
R"RNBOLIT(",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 25,
      "name": "sus",
      "paramId": "mainSynthVoice/sus",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "vis)RNBOLIT"
R"RNBOLIT(ible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 26,
      "name": "1/sus",
      "paramId": "mainSynthVoice/1/sus",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "io)RNBOLIT"
R"RNBOLIT(Type": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 27,
      "name": "2/sus",
      "paramId": "mainSynthVoice/2/sus",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type)RNBOLIT"
R"RNBOLIT(": "ParameterTypeNumber",
      "index": 28,
      "name": "3/sus",
      "paramId": "mainSynthVoice/3/sus",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 29,
    )RNBOLIT"
R"RNBOLIT(  "name": "rel",
      "paramId": "mainSynthVoice/rel",
      "minimum": 0.1,
      "maximum": 2000,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 30,
      "name": "1/rel",
      "paramId": "mainSynthVo)RNBOLIT"
R"RNBOLIT(ice/1/rel",
      "minimum": 0.1,
      "maximum": 2000,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 31,
      "name": "2/rel",
      "paramId": "mainSynthVoice/2/rel",
      "minimum": 0.1,
      "max)RNBOLIT"
R"RNBOLIT(imum": 2000,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 32,
      "name": "3/rel",
      "paramId": "mainSynthVoice/3/rel",
      "minimum": 0.1,
      "maximum": 2000,
      "exponent": 1,
      "ste)RNBOLIT"
R"RNBOLIT(ps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 33,
      "name": "slide",
      "paramId": "BassLine/slide",
      "minimum": 0,
      "maximum": 100,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": fals)RNBOLIT"
R"RNBOLIT(e,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 34,
      "name": "atk",
      "paramId": "BassLine/atk",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
   )RNBOLIT"
R"RNBOLIT(   "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 35,
      "name": "dec",
      "paramId": "BassLine/dec",
      "minimum": 0.1,
      "maximum": 200,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
)RNBOLIT"
R"RNBOLIT(      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 36,
      "name": "sus",
      "paramId": "BassLine/sus",
      "minimum": 0,
      "maximum": 1,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "io)RNBOLIT"
R"RNBOLIT(Type": "IOTypeUndefined"
    },
    {
      "type": "ParameterTypeNumber",
      "index": 37,
      "name": "rel",
      "paramId": "BassLine/rel",
      "minimum": 0.1,
      "maximum": 2000,
      "exponent": 1,
      "steps": 0,
      "initialValue": 0,
      "isEnum": false,
      "enumValues": [],
      "displayName": "",
      "unit": "",
      "order": 0,
      "debug": false,
      "visible": true,
      "signalIndex": null,
      "ioType": "IOTypeUndefined"
    }
  ],
  "numParameters":)RNBOLIT"
R"RNBOLIT( 38,
  "numSignalInParameters": 0,
  "numSignalOutParameters": 0,
  "numInputChannels": 0,
  "numOutputChannels": 2,
  "numMidiInputPorts": 0,
  "numMidiOutputPorts": 0,
  "transportUsed": false,
  "externalDataRefs": [],
  "patcherSerial": 0,
  "inports": [
    {
      "tag": "in2",
      "meta": ""
    },
    {
      "tag": "in3",
      "meta": ""
    },
    {
      "tag": "in4",
      "meta": ""
    },
    {
      "tag": "in5",
      "meta": ""
    }
  ],
  "outports": [
    {
      "tag": "o)RNBOLIT"
R"RNBOLIT(ut3",
      "meta": ""
    },
    {
      "tag": "out4",
      "meta": ""
    },
    {
      "tag": "out5",
      "meta": ""
    },
    {
      "tag": "out6",
      "meta": ""
    }
  ],
  "inlets": [
    {
      "type": "event",
      "index": 2,
      "tag": "in2",
      "meta": "",
      "comment": "Synth Seq In"
    },
    {
      "type": "event",
      "index": 3,
      "tag": "in3",
      "meta": "",
      "comment": "Bass Seq In"
    },
    {
      "type": "event",
      "index": 4,
     )RNBOLIT"
R"RNBOLIT( "tag": "in4",
      "meta": "",
      "comment": "Kck Seq In"
    },
    {
      "type": "event",
      "index": 5,
      "tag": "in5",
      "meta": "",
      "comment": "Hat Seq In"
    }
  ],
  "outlets": [
    {
      "type": "signal",
      "index": 1,
      "tag": "out1",
      "meta": ""
    },
    {
      "type": "signal",
      "index": 2,
      "tag": "out2",
      "meta": ""
    },
    {
      "type": "event",
      "index": 3,
      "tag": "out3",
      "meta": "",
      "comment": )RNBOLIT"
R"RNBOLIT("Melody Sequence"
    },
    {
      "type": "event",
      "index": 4,
      "tag": "out4",
      "meta": "",
      "comment": "Bass Sequence"
    },
    {
      "type": "event",
      "index": 5,
      "tag": "out5",
      "meta": "",
      "comment": "Bass Sequence"
    },
    {
      "type": "event",
      "index": 6,
      "tag": "out6",
      "meta": "",
      "comment": "Hat Sequence"
    }
  ],
  "presetid": "rnbo",
  "meta": {
    "architecture": "x64",
    "filename": "2025-03-06_Hopki)RNBOLIT"
R"RNBOLIT(nsSeq.maxpat",
    "rnboobjname": "rnbomatic",
    "maxversion": "9.0.5",
    "rnboversion": "1.3.4",
    "name": "seqv2"
  }
})RNBOLIT"
			)
		);

	const nlohmann::json patcher_presets = nlohmann::json::parse(
			std::string(
				R"RNBOLIT({})RNBOLIT"
			)
		);
}

#endif
